name: tagsim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1 # Pour gérer les permissions (contacts)
  flutter_contacts: ^1.1.9   # Pour accéder aux contacts (remplace contacts_service)
  url_launcher: ^6.3.0       # Pour rediriger vers l'application d'appel
  google_mobile_ads: ^5.1.0 # Pour AdMob
  in_app_purchase: ^3.2.0    # Pour les achats in-app (version premium)
  share_plus: ^9.0.0         # Pour le bouton de partage
  shared_preferences: ^2.2.3 # Pour sauvegarder les préférences (config SIM)
  libphonenumber_plugin: ^0.3.3 # Pour analyser les numéros et obtenir le pays
  emoji_flag_converter: ^1.0.2 # Pour convertir code pays en drapeau emoji

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/ussd_data.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
