name: Build Android APK

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 - this action also sets environment variables like JAVA_HOME_17_X64
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use stable channel, or match project's channel

      - name: Install Flutter dependencies
        run: flutter pub get

      # Apply patch to call_log using standard patch command
      - name: Apply patch to call_log
        run: |
          # Find the call_log build.gradle file path
          CALL_LOG_BUILD_GRADLE=$(find $HOME/.pub-cache/hosted/pub.dev/call_log-4.0.0* -name build.gradle | head -n 1)
          if [ -z "$CALL_LOG_BUILD_GRADLE" ]; then
            echo "Error: call_log build.gradle not found in .pub-cache"
            exit 1
          fi
          echo "Applying patch to $CALL_LOG_BUILD_GRADLE"
          # Apply the patch (ensure patch file uses relative paths or is applied from correct dir)
          # Assuming the patch was created relative to the package root, we apply it from there
          # However, our patch was created with full paths, let's try applying directly
          patch "$CALL_LOG_BUILD_GRADLE" < patches/call_log+4.0.0.patch

      # Optional: Run tests
      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        # Explicitly set JAVA_HOME for this step using the output from setup-java
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: flutter build apk --release
        # The output APK is typically in build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

