name: Build Android APK

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch
      - features-v2 # Also trigger on features-v2
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 - this action also sets environment variables like JAVA_HOME_17_X64
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Updated to a version with Dart SDK >= 3.4.3

      - name: Install Flutter dependencies
        run: flutter pub get

      # Optional: Run tests
      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        # Explicitly set JAVA_HOME for this step using the output from setup-java
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: flutter build apk --release
        # The output APK is typically in build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

