name: Build Android APK

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 - this action also sets environment variables like JAVA_HOME_17_X64
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use stable channel, or match project's channel

      # Set up Node.js to use patch-package
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or a version compatible with patch-package

      - name: Install Flutter dependencies
        run: flutter pub get

      # Install Node.js dependencies (including patch-package)
      - name: Install Node dependencies
        run: npm install

      # Apply patches using patch-package
      - name: Apply patches
        run: npx patch-package --patch-dir patches

      # Optional: Run tests
      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        # Explicitly set JAVA_HOME for this step using the output from setup-java
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: flutter build apk --release
        # The output APK is typically in build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

